# DO NOT MODIFY THIS FILE
# Generated by Bundler 0.9.19

require 'digest/sha1'
require 'pathname'
require 'rubygems'
Gem.source_index # ensure Rubygems is fully loaded in Ruby 1.9

module Gem
  class Dependency
    if !instance_methods.map { |m| m.to_s }.include?("requirement")
      def requirement
        version_requirements
      end
    end
  end
end

module Bundler
  class Specification < Gem::Specification
    attr_accessor :relative_loaded_from

    def self.from_gemspec(gemspec)
      spec = allocate
      gemspec.instance_variables.each do |ivar|
        spec.instance_variable_set(ivar, gemspec.instance_variable_get(ivar))
      end
      spec
    end

    def loaded_from
      return super unless relative_loaded_from
      source.path.join(relative_loaded_from).to_s
    end

    def full_gem_path
      Pathname.new(loaded_from).dirname.expand_path.to_s
    end

  end

  module SharedHelpers
    attr_accessor :gem_loaded

    def default_gemfile
      gemfile = find_gemfile
      gemfile or raise GemfileNotFound, "Could not locate Gemfile"
      Pathname.new(gemfile)
    end

    def in_bundle?
      find_gemfile
    end

    def env_file
      default_gemfile.dirname.join(".bundle/environment.rb")
    end

  private

    def find_gemfile
      return ENV['BUNDLE_GEMFILE'] if ENV['BUNDLE_GEMFILE']

      previous = nil
      current  = File.expand_path(Dir.pwd)

      until !File.directory?(current) || current == previous
        filename = File.join(current, 'Gemfile')
        return filename if File.file?(filename)
        current, previous = File.expand_path("..", current), current
      end
    end

    def clean_load_path
      # handle 1.9 where system gems are always on the load path
      if defined?(::Gem)
        me = File.expand_path("../../", __FILE__)
        $LOAD_PATH.reject! do |p|
          next if File.expand_path(p).include?(me)
          p != File.dirname(__FILE__) &&
            Gem.path.any? { |gp| p.include?(gp) }
        end
        $LOAD_PATH.uniq!
      end
    end

    def reverse_rubygems_kernel_mixin
      # Disable rubygems' gem activation system
      ::Kernel.class_eval do
        if private_method_defined?(:gem_original_require)
          alias rubygems_require require
          alias require gem_original_require
        end

        undef gem
      end
    end

    def cripple_rubygems(specs)
      reverse_rubygems_kernel_mixin

      executables = specs.map { |s| s.executables }.flatten
      Gem.source_index # ensure RubyGems is fully loaded

     ::Kernel.class_eval do
        private
        def gem(*) ; end
      end

      ::Kernel.send(:define_method, :gem) do |dep, *reqs|
        if executables.include? File.basename(caller.first.split(':').first)
          return
        end
        opts = reqs.last.is_a?(Hash) ? reqs.pop : {}

        unless dep.respond_to?(:name) && dep.respond_to?(:requirement)
          dep = Gem::Dependency.new(dep, reqs)
        end

        spec = specs.find  { |s| s.name == dep.name }

        if spec.nil?
          e = Gem::LoadError.new "#{dep.name} is not part of the bundle. Add it to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        elsif dep !~ spec
          e = Gem::LoadError.new "can't activate #{dep}, already activated #{spec.full_name}. " \
                                 "Make sure all dependencies are added to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        end

        true
      end

      # === Following hacks are to improve on the generated bin wrappers ===

      # Yeah, talk about a hack
      source_index_class = (class << Gem::SourceIndex ; self ; end)
      source_index_class.send(:define_method, :from_gems_in) do |*args|
        source_index = Gem::SourceIndex.new
        source_index.spec_dirs = *args
        source_index.add_specs(*specs)
        source_index
      end

      # OMG more hacks
      gem_class = (class << Gem ; self ; end)
      gem_class.send(:define_method, :bin_path) do |name, *args|
        exec_name, *reqs = args

        spec = nil

        if exec_name
          spec = specs.find { |s| s.executables.include?(exec_name) }
          spec or raise Gem::Exception, "can't find executable #{exec_name}"
        else
          spec = specs.find  { |s| s.name == name }
          exec_name = spec.default_executable or raise Gem::Exception, "no default executable for #{spec.full_name}"
        end

        gem_bin = File.join(spec.full_gem_path, spec.bindir, exec_name)
        gem_from_path_bin = File.join(File.dirname(spec.loaded_from), spec.bindir, exec_name)
        File.exist?(gem_bin) ? gem_bin : gem_from_path_bin
      end
    end

    extend self
  end
end

module Bundler
  LOCKED_BY    = '0.9.19'
  FINGERPRINT  = "edca32f4fe9e08af4786be71aed8d5692b10b653"
  HOME         = '/Users/jpemberthy/.bundle/ruby/1.8/bundler'
  AUTOREQUIRES = {:test=>[["factory_girl", false], ["mocha", false], ["rspec-rails", false]], :default=>[["acts-as-taggable-on", false], ["haml", false], ["compass", false], ["mongo", false], ["mongo_ext", false], ["will_paginate", false], ["mongoid", false], ["mysql", false], ["rails", false]], :development=>[["hirb", false], ["ruby-debug", false]]}
  SPECS        = [
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rake-0.8.7.gemspec", :name=>"rake", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rake-0.8.7/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/abstract-1.0.0.gemspec", :name=>"abstract", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/abstract-1.0.0/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/builder-2.1.2.gemspec", :name=>"builder", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/builder-2.1.2/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/i18n-0.3.6.gemspec", :name=>"i18n", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/i18n-0.3.6/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/memcache-client-1.7.8.gemspec", :name=>"memcache-client", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/memcache-client-1.7.8/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/tzinfo-0.3.19.gemspec", :name=>"tzinfo", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/tzinfo-0.3.19/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/activesupport-3.0.0.beta.gemspec", :name=>"activesupport", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/activesupport-3.0.0.beta/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/activemodel-3.0.0.beta.gemspec", :name=>"activemodel", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/activemodel-3.0.0.beta/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/erubis-2.6.5.gemspec", :name=>"erubis", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/erubis-2.6.5/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rack-1.1.0.gemspec", :name=>"rack", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rack-1.1.0/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rack-mount-0.4.7.gemspec", :name=>"rack-mount", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rack-mount-0.4.7/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rack-test-0.5.3.gemspec", :name=>"rack-test", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rack-test-0.5.3/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/actionpack-3.0.0.beta.gemspec", :name=>"actionpack", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/actionpack-3.0.0.beta/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/mime-types-1.16.gemspec", :name=>"mime-types", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/mime-types-1.16/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/polyglot-0.3.1.gemspec", :name=>"polyglot", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/polyglot-0.3.1/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/treetop-1.4.5.gemspec", :name=>"treetop", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/treetop-1.4.5/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/mail-2.1.5.3.gemspec", :name=>"mail", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/mail-2.1.5.3/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/text-hyphen-1.0.0.gemspec", :name=>"text-hyphen", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/text-hyphen-1.0.0/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/text-format-1.0.0.gemspec", :name=>"text-format", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/text-format-1.0.0/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/actionmailer-3.0.0.beta.gemspec", :name=>"actionmailer", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/actionmailer-3.0.0.beta/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/arel-0.2.1.gemspec", :name=>"arel", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/arel-0.2.1/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/activerecord-3.0.0.beta.gemspec", :name=>"activerecord", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/activerecord-3.0.0.beta/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/activeresource-3.0.0.beta.gemspec", :name=>"activeresource", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/activeresource-3.0.0.beta/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/acts-as-taggable-on-2.0.0.rc1.gemspec", :name=>"acts-as-taggable-on", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/acts-as-taggable-on-2.0.0.rc1/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.rvm/gems/ruby-1.8.7-p72%lhvac/specifications/bundler-0.9.19.gemspec", :name=>"bundler", :load_paths=>["/Users/jpemberthy/.rvm/gems/ruby-1.8.7-p72%lhvac/gems/bundler-0.9.19/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/columnize-0.3.1.gemspec", :name=>"columnize", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/columnize-0.3.1/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/haml-2.2.23.gemspec", :name=>"haml", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/haml-2.2.23/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/compass-0.10.0.rc1.gemspec", :name=>"compass", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/compass-0.10.0.rc1/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/bundler/gems/factory_girl-511843606ed9fcb0d1005a7b7b4e9598b07eae20-feac7298352a83fef0717d8beadd2eda9aabfe56/factory_girl.gemspec", :name=>"factory_girl", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/bundler/gems/factory_girl-511843606ed9fcb0d1005a7b7b4e9598b07eae20-feac7298352a83fef0717d8beadd2eda9aabfe56/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/hirb-0.3.1.gemspec", :name=>"hirb", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/hirb-0.3.1/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/linecache-0.43.gemspec", :name=>"linecache", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/linecache-0.43/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/mocha-0.9.8.gemspec", :name=>"mocha", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/mocha-0.9.8/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/mongo-0.19.1.gemspec", :name=>"mongo", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/mongo-0.19.1/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/mongo_ext-0.19.1.gemspec", :name=>"mongo_ext", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/mongo_ext-0.19.1/ext"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/will_paginate-3.0.pre.gemspec", :name=>"will_paginate", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/will_paginate-3.0.pre/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/mongoid-2.0.0.alpha.gemspec", :name=>"mongoid", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/mongoid-2.0.0.alpha/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/mysql-2.8.1.gemspec", :name=>"mysql", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/mysql-2.8.1/lib", "/Users/jpemberthy/.bundle/ruby/1.8/gems/mysql-2.8.1/ext"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/nokogiri-1.4.1.gemspec", :name=>"nokogiri", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/nokogiri-1.4.1/lib", "/Users/jpemberthy/.bundle/ruby/1.8/gems/nokogiri-1.4.1/ext"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/thor-0.13.4.gemspec", :name=>"thor", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/thor-0.13.4/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/railties-3.0.0.beta.gemspec", :name=>"railties", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/railties-3.0.0.beta/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rails-3.0.0.beta.gemspec", :name=>"rails", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rails-3.0.0.beta/"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rspec-core-2.0.0.beta.4.gemspec", :name=>"rspec-core", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rspec-core-2.0.0.beta.4/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rspec-expectations-2.0.0.beta.4.gemspec", :name=>"rspec-expectations", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rspec-expectations-2.0.0.beta.4/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rspec-mocks-2.0.0.beta.4.gemspec", :name=>"rspec-mocks", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rspec-mocks-2.0.0.beta.4/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rspec-2.0.0.beta.4.gemspec", :name=>"rspec", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rspec-2.0.0.beta.4/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/webrat-0.7.0.gemspec", :name=>"webrat", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/webrat-0.7.0/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/rspec-rails-2.0.0.beta.4.gemspec", :name=>"rspec-rails", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/rspec-rails-2.0.0.beta.4/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/ruby-debug-base-0.10.3.gemspec", :name=>"ruby-debug-base", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/ruby-debug-base-0.10.3/lib"]},
        {:loaded_from=>"/Users/jpemberthy/.bundle/ruby/1.8/specifications/ruby-debug-0.10.3.gemspec", :name=>"ruby-debug", :load_paths=>["/Users/jpemberthy/.bundle/ruby/1.8/gems/ruby-debug-0.10.3/cli"]},
      ].map do |hash|
    if hash[:virtual_spec]
      spec = eval(hash[:virtual_spec], TOPLEVEL_BINDING, "<virtual spec for '#{hash[:name]}'>")
    else
      dir = File.dirname(hash[:loaded_from])
      spec = Dir.chdir(dir){ eval(File.read(hash[:loaded_from]), TOPLEVEL_BINDING, hash[:loaded_from]) }
    end
    spec.loaded_from = hash[:loaded_from]
    spec.require_paths = hash[:load_paths]
    if spec.loaded_from.include?(HOME)
      Bundler::Specification.from_gemspec(spec)
    else
      spec
    end
  end

  extend SharedHelpers

  def self.configure_gem_path_and_home(specs)
    # Fix paths, so that Gem.source_index and such will work
    paths = specs.map{|s| s.installation_path }
    paths.flatten!; paths.compact!; paths.uniq!; paths.reject!{|p| p.empty? }
    ENV['GEM_PATH'] = paths.join(File::PATH_SEPARATOR)
    ENV['GEM_HOME'] = paths.first
    Gem.clear_paths
  end

  def self.match_fingerprint
    print = Digest::SHA1.hexdigest(File.read(File.expand_path('../../Gemfile', __FILE__)))
    unless print == FINGERPRINT
      abort 'Gemfile changed since you last locked. Please `bundle lock` to relock.'
    end
  end

  def self.setup(*groups)
    match_fingerprint
    clean_load_path
    cripple_rubygems(SPECS)
    configure_gem_path_and_home(SPECS)
    SPECS.each do |spec|
      Gem.loaded_specs[spec.name] = spec
      spec.require_paths.each do |path|
        $LOAD_PATH.unshift(path) unless $LOAD_PATH.include?(path)
      end
    end
    self
  end

  def self.require(*groups)
    groups = [:default] if groups.empty?
    groups.each do |group|
      (AUTOREQUIRES[group.to_sym] || []).each do |file, explicit|
        if explicit
          Kernel.require file
        else
          begin
            Kernel.require file
          rescue LoadError
          end
        end
      end
    end
  end

  # Set up load paths unless this file is being loaded after the Bundler gem
  setup unless @gem_loaded
end
