defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: lhvac_development

test:
  <<: *defaults
  database: lhvac_test

# production:
#   <<: *defaults
#   host: db.mongohq.com
#   username: user
#   password: pass
#   database: fanboy
