defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: lhvac_developmen

# production:
#   <<: *defaults
#   host: db.mongohq.com
#   username: user
#   password: pass
#   database: fanboy