defaults: &defaults
  host: localhost
  
development:
  <<: *defaults
  database: lhvac_development

test:
  <<: *defaults
  database: lhvac_test

production:
  <<: *defaults
  database: hvac_production
