development:
  host: development.lhvac.com
  from: test@lhvac.com
  fconnect_site_id: 18322011899239412358
  
test:
  host: test.lhvac.com
  from: test@lhvac.com
  fconnect_site_id: 18322011899239412358
  
production:
  host: app.learnhvac.org
  from: app@learnhvac.org
  fconnect_site_id: 08223197587884952724
